In [1]:
import numpy as np 

# Creating arrays

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))   # <class 'numpy.ndarray'>

# Key difference from lists - NumPy arrays are vectorized
numbers = [1,2,3,4,5]
print(numbers * 2)    # [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] — list duplication
print(arr * 2)        # [2, 4, 6, 8, 10] — element-wise multiplication

# 2D arrays - similar to matrices
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix.shape)   # (3, 3) — 3 rows, 3 columns
print(matrix[0])      # first row — [1, 2, 3]
print(matrix[0, 1])   # row 0, column 1-2
print(matrix[:, 1])   # all rows, column 1 - [2,5,8]

# Useful array creation functions
print(np.zeros((3,3)))     # 3x3 matrix of zeros
print(np.ones((2, 4)))     # 2x4 matrix of ones
print(np.arange(0, 10, 2)) # [0, 2, 4, 6, 8]
print(np.linspace(0, 1, 5))# 5 evenly spaced values between 0 and 1

# Statistical operations
arr = np.array([88, 92, 75, 100, 61, 79])
print(np.mean(arr))       # mean
print(np.median(arr))     # median
print(np.std(arr))        # standard deviation
print(np.min(arr))        # minimum
print(np.max(arr))        # maximum

[1 2 3 4 5]
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
(3, 3)
[1 2 3]
2
[2 5 8]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
82.5
83.5
12.632629707758133
61
100


In [4]:
# Practice

# 1. Create a NumPy array of numbers 1–20

numbers = np.arange(1,21,1)
print(numbers)

# 2. Calculate the mean, median, and standard deviation

print(np.mean(numbers))
print(np.median(numbers))
print(round(np.std(numbers),2))

# 3. Create a 3x3 matrix of random integers between 1 and 10

random = np.random.randint(1,10,size=(3,3))

# 4. Select the second row of the matrix

print(random[1])

# 5. Multiply every element in your 1–20 array by 3
#    using vectorized operations (no loops!)

print(numbers * 3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
10.5
10.5
5.77
[9 1 1]
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]


In [9]:
import pandas as pd 

df = pd.read_csv("titanic.csv")

# Selecting columns
print(df["Age"])   # single column - returns Series
print(df[["Age", "Survived"]])   # multiple columns - returns DataFrame

# Filtering rows
adults = df[df["Age"] >= 18]
survivors = df[df["Survived"] == 1]
female_survivors = df[(df["Survived"] == 1) & (df["Sex"] == "female")]

# Adding new columns
df["AgeGroup"] = df["Age"].apply(lambda x: "Adult" if x>= 18 else "Minor")

# Handling missing values 
print(df.isnull().sum())   # count missing values
df["Age"].fillna(df["Age"].mean())  # fill missing with mean
df.dropna(subset=["Age"])           # drop rows where Age is missing

# Groupby - aggregation
print(df.groupby("Sex")["Survived"].mean())
print(df.groupby("Pclass")["Age"].mean())
print(df.groupby(["Sex", "Pclass"])["Survived"].mean())

# Value counts and sorting
print(df["Pclass"].value_counts())
print(df.sort_values("Age", ascending=False).head())

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
      Age  Survived
0    22.0         0
1    38.0         1
2    26.0         1
3    35.0         1
4    35.0         0
..    ...       ...
886  27.0         0
887  19.0         1
888   NaN         0
889  26.0         1
890  32.0         0

[891 rows x 2 columns]
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
AgeGroup         0
dtype: int64
Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64
Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64
Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
    

In [16]:
# Practice

# 1. Create a new column called "FamilySize" that adds
#    "SibSp" (siblings/spouses) and "Parch" (parents/children) together

df["FamilySize"] = df["SibSp"] + df["Parch"]
print(df[["SibSp", "Parch", "FamilySize"]].head())

# 2. What was the survival rate for each passenger class?
#    Use groupby — express as a percentage rounded to 2 decimal places

print(round(df.groupby("Pclass")["Survived"].mean() * 100, 2))

# 3. Fill missing Age values with the median age
#    Then confirm no missing values remain in the Age column

df["Age"] = df["Age"].fillna(df["Age"].median())
print(df["Age"].isnull().sum())

# 4. Create a new column called "AgeGroup":
#    "Child" for age < 18, "Adult" for 18–60, "Senior" for > 60

df["AgeGroup"] = df["Age"].apply(lambda x: "Senior" if x>60 else ("Adult" if x>= 18 else "Child"))
print(df["AgeGroup"].value_counts())

# 5. What was the survival rate for each AgeGroup?
#    Use groupby

print(round(df.groupby("AgeGroup")["Survived"].mean() * 100, 2))

   SibSp  Parch  FamilySize
0      1      0           1
1      1      0           1
2      0      0           0
3      1      0           1
4      0      0           0
Pclass
1    62.96
2    47.28
3    24.24
Name: Survived, dtype: float64
0
AgeGroup
Adult     756
Child     113
Senior     22
Name: count, dtype: int64
AgeGroup
Adult     36.51
Child     53.98
Senior    22.73
Name: Survived, dtype: float64
